# Build
- docker build -t reverseproxy .

# Tagging
- docker tag reverseproxy tatthang0501/reverseproxy:v1
# Do similar for other three images

# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push tatthang0501/reverseproxy:v1
# Do similar for other three images